name: WaelTest3

on: [push]

jobs:
  run_tests:
    runs-on: macos-12
    strategy:
      matrix:
        include:
          - xcode: "14.2"
            ios: "16.2"
          - xcode: "14.2"
            ios: "16.2"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: |
        go test 
